---
- hosts: linuxservers
  become: yes

  vars:
      package:
         - httpd
         - mariadb-server
         - php
         - php-mysqlnd

  tasks:

  - name: Is httpd running
    debug:
      msg: httpd is running
    when: httpd_status.state == "started"
  - name: Show Status
    debug:
      var: httpd_status